# -*- coding: utf-8 -*-
"""Abacus Questionnaire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x2Tmk6sRytQ5AgC374JGoxTXgB8z4T-
"""

import streamlit as st
import random

# Abacus Question Generator Code
def generate_question():
    num1 = random.randint(1, 99)
    num2 = random.randint(1, 99)
    operation = random.choice(['+', '-'])
    question = f"{num1} {operation} {num2}"
    answer = eval(question)
    return question, answer

# Generate 20 questions
questions = []
for _ in range(20):
    question, answer = generate_question()
    questions.append((question, answer))

# Streamlit app to display questions and collect answers
st.title("Abacus Questionnaire")

student_answers = []

for i, (question, correct_answer) in enumerate(questions):
    st.write(f"Question {i + 1}: {question}")

    # Display multiple choice answers
    answer = st.radio(f"Choose the answer for Question {i + 1}", [correct_answer - 1, correct_answer, correct_answer + 1])

    # Add the answer to the list
    student_answers.append((answer, correct_answer))

# After all answers are submitted, show the result
if len(student_answers) == 20:
    score = sum(1 for ans, correct in student_answers if ans == correct)
    st.write(f"You got {score} out of 20 correct!")