# -*- coding: utf-8 -*-
"""Abacus Questionnaire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x2Tmk6sRytQ5AgC374JGoxTXgB8z4T-
"""

import random
import streamlit as st

def generate_question():
    """Generates a simple addition or subtraction question with 1-2 digit numbers."""
    num1 = random.randint(1, 99)
    num2 = random.randint(1, 99)
    operation = random.choice(["+", "-"])
    if operation == "-" and num1 < num2:  # Ensure no negative results
        num1, num2 = num2, num1
    correct_answer = eval(f"{num1} {operation} {num2}")
    choices = [correct_answer]
    while len(choices) < 4:
        fake_answer = random.randint(correct_answer - 10, correct_answer + 10)
        if fake_answer != correct_answer and fake_answer not in choices:
            choices.append(fake_answer)
    random.shuffle(choices)
    question = f"What is {num1} {operation} {num2}?"
    return question, correct_answer, choices

# Streamlit UI
st.title("Abacus Quiz")
st.write("Answer the following questions:")

if "score" not in st.session_state:
    st.session_state.score = 0
    st.session_state.question_idx = 0
    st.session_state.total_questions = 20
    st.session_state.questions = [generate_question() for _ in range(20)]

if st.session_state.question_idx < st.session_state.total_questions:
    question, correct_answer, choices = st.session_state.questions[st.session_state.question_idx]
    st.write(f"Question {st.session_state.question_idx + 1}: {question}")
    user_answer = st.radio("Choose your answer:", choices, key=st.session_state.question_idx)

    if st.button("Submit Answer"):
        if user_answer == correct_answer:
            st.session_state.score += 1
            st.success("Correct!")
        else:
            st.error(f"Wrong! The correct answer was {correct_answer}.")
        st.session_state.question_idx += 1
        st.experimental_rerun()
else:
    st.write(f"Quiz completed! Your score is {st.session_state.score}/{st.session_state.total_questions}.")
    if st.button("Restart Quiz"):
        st.session_state.clear()