# -*- coding: utf-8 -*-
"""Abacus Questionnaire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x2Tmk6sRytQ5AgC374JGoxTXgB8z4T-
"""

import streamlit as st
import random

# Abacus Question Generator Code
def generate_question():
    num1 = random.randint(1, 99)
    num2 = random.randint(1, 99)
    operation = random.choice(['+', '-'])
    question = f"{num1} {operation} {num2}"
    answer = eval(question)
    return question, answer

# Generate 20 questions
questions = []
for _ in range(10):
    question, answer = generate_question()
    questions.append((question, answer))

# Display all questions at once
st.title("Abacus Question Paper")

# Dictionary to store user answers
user_answers = {}

# Iterate through questions and display them
for idx, (question, correct_answer) in enumerate(questions):
    # Use radio buttons for each question
    user_answer = st.radio(f"Question {idx + 1}: {question}",
                           options=[correct_answer - 1, correct_answer, correct_answer + 1],
                           key=f"question_{idx}")
    user_answers[idx] = user_answer

# Button to submit all answers at once
submit_button = st.button("Submit Answers")

# When the submit button is pressed, show results
if submit_button:
    score = 0
    # Calculate score based on user answers
    for idx, (question, correct_answer) in enumerate(questions):
        if user_answers[idx] == correct_answer:
            score += 1

    # Display the result
    st.write(f"You got {score} out of 10 correct!")